### ISSUE TITLE
Buttons in code laten zien ipv fotos.

### ISSUE THREAD

**Issue by Patrickkhr** [yujing-student/look-and-feel-living-styleguide#13]
Misschien is het handig om de buttons met code op de website te laten zien in plaats van met fotos.

**Comment by yujing-student** [comment]
https://github.com/yujing-student/look-and-feel-living-styleguide/blob/2a85e857c5562a23a505804de34388f222c65c45/index.html#L687-L689 

https://github.com/yujing-student/look-and-feel-living-styleguide/blob/2a85e857c5562a23a505804de34388f222c65c45/style.css#L459-L462

Dit heb ik toegevoegd
