### ISSUE TITLE
buttons niet duidelijk

### ISSUE THREAD

**Issue by RukiyaTossou** [yujing-student/look-and-feel-living-styleguide#14]
Je kan bij sommige buttons niet zien dat het een button is. Misschien zou je een hover kunnen toevoegen zodat het duidelijk is dat het geen foto is maar echt een button.

**Comment by yujing-student** [comment]
![image](https://github.com/yujing-student/look-and-feel-living-styleguide/assets/100352887/75d3d44d-7c46-4a65-89b5-ff02b1ce9af3)
hover is toegevoegd
