### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Shannafdnd** [yujing-student/look-and-feel-living-styleguide#7]
_https://github.com/yujing-student/look-and-feel-living-styleguide/blob/e506bd9dc1f2baf0a5139d70c87642ce203d984d/index.html#L328C92-L328C92_
Zeer goed naar de opdrachtgever geluisterd en zijn feedback verwerkt in de styleguide. 

_https://github.com/yujing-student/look-and-feel-living-styleguide/blob/e506bd9dc1f2baf0a5139d70c87642ce203d984d/index.html#L365_
Hier zou ik de alt een betere beschrijving geven, bijv.: oba jeugd image

**Comment by wingsvn** [comment]
alt aangepast naar jeugd 0-6 jaar
